dist: xenial
language: go
go:
    - "1.12"
services:
    - mysql

before_install:
      - mysql -e 'CREATE DATABASE IF NOT EXISTS service_exceptions_test;'
install:
      - ./install.sh
script:
      - ./test.sh

